"""Measure node accelerator energy around a command this repo did not write.

    python analysis/power_sidecar.py --out results/aiperf/aurora-x/c8.power.json \
        -- aiperf profile --model ... --url ...

The training benchmark samples power from inside its own process, because it
owns the loop and can mark epoch boundaries on the timeline. An inference
benchmark cannot: the load is generated by AIPerf and served by vLLM, two
processes this package neither starts nor imports. AIPerf does collect power
itself, but only through DCGM, pynvml and amdsmi -- there is no XPU path, which
is why the README says Aurora is out of the inference benchmark.

It is out of *AIPerf's* power collection. The counters are still there in sysfs,
and reading them does not require being the process under test. So this samples
them from beside the run instead of inside it, and the tokens/joule that AIPerf
cannot compute on Intel silicon becomes a division done afterwards: AIPerf's
token counts over these joules.

What this does NOT measure, stated because the number looks the same either way:
this is whole-node accelerator energy for the wall-clock window the command ran
in. On an exclusive node serving one model that is the energy of serving. On a
shared node, or with anything else resident, it is that plus whatever else was
running. Check the node is yours before quoting a figure.

Stdlib only, so it runs inside the AIPerf virtualenv without adding a dependency
-- which is the whole reason the sysfs walk moved to benchmark/hwmon.py, away
from platform.py and its module-scope torch import.
"""

from __future__ import annotations

import argparse
import json
import os
import socket
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# Import the package directly rather than through analysis/, which is a
# directory of scripts and not a package. Running this file from the repo root
# is enough; running it from elsewhere needs PYTHONPATH.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from benchmark.power import PowerSampler  # noqa: E402


def build_sources(machine: str):
    """Energy counters for this machine, or an empty list with a reason.

    NVIDIA is supported even though AIPerf reads NVML itself. Running both is
    the point: Polaris is the only machine where this sidecar can be checked
    against an independent instrument measuring the same devices, and Aurora --
    which has no second opinion available at all -- depends on the method being
    right. It also fills the bound/idle split, which AIPerf does not report.

    device_index is the NVML index here, not torch's. A sidecar binds nothing,
    and --bound-devices names physical devices.
    """
    if machine == "aurora":
        from benchmark.hwmon import intel_energy_sources

        return intel_energy_sources(), "intel i915 hwmon energy1_input"

    from benchmark.nvml import nvml_energy_sources

    sources = nvml_energy_sources(visible=None)
    if sources:
        # Named from what the counters actually are, not assumed: an A100 has
        # the energy counter, something older silently integrates power instead
        # and the scope string is the only place that difference shows.
        kind = sources[0].scope.split("(")[-1].rstrip(")")
        return sources, f"nvml, {len(sources)} device(s), {kind}"
    raise SystemExit(
        f"no readable energy counter for machine '{machine}'.\n"
        "  aurora: i915 hwmon counters under /sys/class/drm\n"
        "  nvidia: pynvml plus a driver -- on a login node there is no driver,\n"
        "          and nvmlInit fails with NVML Shared Library Not Found.\n"
        "  crux and other CPU-only machines have nothing to read."
    )


# Substring -> machine, checked against PBS_JOBID and the hostname. Same
# approach as platform.py's _alcf_machine: the scheduler stamps the machine into
# both, and it is the only thing on a compute node that names it.
_MACHINE_HINTS = ("polaris", "sophia", "aurora", "crux")


def detect_machine() -> str | None:
    """The machine, from its counters where possible and its name where not.

    Intel counters identify Aurora on their own -- no other machine here has
    them. NVML cannot distinguish Polaris from Sophia, since both are A100s, so
    that falls back to PBS_JOBID and the hostname. A guess is acceptable for the
    label; it is not acceptable for the counters, which is why the label is the
    only thing guessed.
    """
    from benchmark.hwmon import intel_energy_counters

    if any(intel_energy_counters()):
        return "aurora"

    from benchmark.nvml import load_nvml

    if load_nvml() is None:
        return None
    haystack = f"{os.environ.get('PBS_JOBID', '')} {socket.gethostname()}".lower()
    return next((m for m in _MACHINE_HINTS if m in haystack), "cuda")


def parse_devices(spec: str, sources) -> frozenset:
    """Which device indices to count as doing the work.

    Defaults to all of them. The training run derives this from the rank-to-
    device binding rule, which does not exist here -- vLLM decides its own
    placement and this process never sees it. On an exclusive node running one
    server, everything on the node is attributable to the run, so 'all' is both
    the honest default and the common case. Name indices explicitly when it is
    not, and the idle columns mean something again.
    """
    indices = {s.device_index for s in sources if s.device_index is not None}
    if spec == "all":
        return frozenset(indices)
    if spec == "none":
        return frozenset()
    return frozenset(int(x) for x in spec.split(",") if x.strip())


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__.splitlines()[0],
        epilog="Everything after -- is the command to run and measure.",
    )
    ap.add_argument("--out", required=True, help="summary JSON to write")
    ap.add_argument("--interval", type=float, default=0.1,
                    help="seconds between counter reads (default 0.1)")
    ap.add_argument("--machine", default=None,
                    help="force the machine; auto-detected from the counters otherwise")
    ap.add_argument("--bound-devices", default="all",
                    help="'all' (default), 'none', or a comma-separated index list")
    ap.add_argument("--label", default=None,
                    help="free-text label recorded in the summary, e.g. the concurrency")
    ap.add_argument("command", nargs=argparse.REMAINDER,
                    help="-- then the command to run")
    args = ap.parse_args()

    command = args.command[1:] if args.command[:1] == ["--"] else args.command
    if not command:
        raise SystemExit("nothing to run: put the command after --")

    machine = args.machine or detect_machine()
    if machine is None:
        raise SystemExit(
            "could not detect the machine: no Intel energy counters under "
            "/sys/class/drm, and no NVIDIA driver for NVML to load.\n"
            "On a login node that is expected -- there is no accelerator to "
            "read. Pass --machine to force one, but a forced machine whose "
            "counters are absent measures nothing."
        )
    sources, scope = build_sources(machine)
    if not sources:
        raise SystemExit(
            f"machine '{machine}' exposes no readable energy counter. Refusing to "
            "run and report zero joules, which reads as a measurement."
        )

    bound = parse_devices(args.bound_devices, sources)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)

    print(f"sidecar: {len(sources)} counter(s) on {machine} via {scope}")
    print(f"         sampling every {args.interval}s while: {' '.join(command)}")

    started = datetime.now(timezone.utc)
    sampler = PowerSampler(sources, interval_s=args.interval, bound_devices=bound).start()
    sampler.mark("command_start")
    t0 = time.perf_counter()
    # The command owns the terminal: AIPerf prints a progress display and its own
    # summary, and swallowing that to capture it would hide a failure behind a
    # sidecar. Exit code is what this process reports on.
    completed = subprocess.run(command)
    wall_s = time.perf_counter() - t0
    sampler.mark("command_end")
    timeline = sampler.stop()

    if not timeline:
        raise SystemExit(
            f"command ran for {wall_s:.1f}s but fewer than two samples were taken; "
            "no energy can be derived from that. Lower --interval, or check the "
            "counters are still readable."
        )

    summary = timeline.summary()
    # The series goes beside the summary under the same stem, matching how the
    # training runs split them: thousands of samples per counter do not belong
    # in a file every analysis script parses.
    series_path = timeline.write(
        out.parent, machine, out.stem.replace(".", "_"), socket.gethostname()
    )

    record = {
        "kind": "power_sidecar",
        "machine": machine,
        "label": args.label,
        "hostname": socket.gethostname(),
        "started_utc": started.isoformat(),
        "wall_s": wall_s,
        "command": command,
        "exit_code": completed.returncode,
        "counter_scope": scope,
        "bound_devices": sorted(bound),
        "series_file": series_path.name,
        "power": summary,
    }
    out.write_text(json.dumps(record, indent=2), encoding="utf-8")

    joules = summary.get("joules_total")
    print(f"\nsidecar: {joules:,.1f} J over {wall_s:,.1f} s "
          f"({joules / wall_s:,.1f} W avg) across {summary['device_count']} device(s)"
          if joules else "\nsidecar: no energy measured")
    print(f"         wrote {out} and {series_path.name}")
    if completed.returncode != 0:
        print(f"         NOTE: the command exited {completed.returncode}; the energy "
              "above covers a run that failed.")
    # Propagate, so a wrapper script's `set -e` still sees the command's failure
    # rather than the sidecar's success at measuring it.
    sys.exit(completed.returncode)


if __name__ == "__main__":
    main()
